services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: template-clinicas-odontologicas-postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: "./backend"
    container_name: template-clinicas-odontologicas-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: "./frontend"
    container_name: template-clinicas-odontologicas-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  postgres_data: