import type { SystemUser } from "./types";

export const MOCK_USERS: SystemUser[] = [
  {
    id: "u1",
    name: "Renata Costa",
    email: "renata.costa@odontosys.com",
    initials: "RC",
    avatarColor: "bg-primary",
    profile: "manager",
    status: "active",
    createdAt: "12/01/2024",
    isSelf: true,
  },
  {
    id: "u2",
    name: "Fernanda Lima",
    email: "fernanda.lima@odontosys.com",
    initials: "FL",
    avatarColor: "#8b5cf6",
    profile: "manager",
    status: "active",
    createdAt: "15/01/2024",
  },
  {
    id: "u3",
    name: "Marcos Silva",
    email: "marcos.silva@odontosys.com",
    initials: "MS",
    avatarColor: "#8b5cf6",
    profile: "dentist",
    status: "active",
    createdAt: "03/02/2024",
  },
  {
    id: "u4",
    name: "Camila Rocha",
    email: "camila.rocha@odontosys.com",
    initials: "CR",
    avatarColor: "#06b6d4",
    profile: "dentist",
    status: "active",
    createdAt: "17/03/2024",
  },
  {
    id: "u5",
    name: "Juliana Ramos",
    email: "juliana.ramos@odontosys.com",
    initials: "JR",
    avatarColor: "bg-primary",
    profile: "receptionist",
    status: "active",
    createdAt: "22/03/2024",
  },
  {
    id: "u6",
    name: "Pedro Alves",
    email: "pedro.alves@odontosys.com",
    initials: "PA",
    avatarColor: "bg-primary",
    profile: "receptionist",
    status: "active",
    createdAt: "02/04/2024",
  },
  {
    id: "u7",
    name: "Orlando Nunes",
    email: "orlando.nunes@odontosys.com",
    initials: "ON",
    avatarColor: "#06b6d4",
    profile: "dentist",
    status: "active",
    createdAt: "20/04/2024",
  },
  {
    id: "u8",
    name: "Felipe Trigo",
    email: "felipe.trigo@odontosys.com",
    initials: "FT",
    avatarColor: "bg-[var(--gray-300)]",
    profile: "dentist",
    status: "inactive",
    createdAt: "11/05/2024",
  },
  {
    id: "u9",
    name: "Bianca Souza",
    email: "bianca.souza@odontosys.com",
    initials: "BS",
    avatarColor: "bg-[var(--gray-300)]",
    profile: "receptionist",
    status: "inactive",
    createdAt: "28/06/2024",
  },
];